<?php

/**
 * @file
 * Install and uninstall callbacks.
 */

/**
 * Implemements hook_uninstall()
 */
function addressfield_validation_fedex_uninstall() {
  variable_del('addressfield_validation_fedex_environment');
  foreach (array ('key', 'account', 'meter', 'password', 'street_accuracy', 'directional_accuracy') as $var) {
    variable_del('addressfield_validation_fedex_test_' . $var);
    variable_del('addressfield_validation_fedex_live_' . $var);
  }
}