<?php

/**
 * @file
 * Install and uninstall callbacks.
 */

/**
 * Implemements hook_install()
 * @todo Remove when hook_addressfield_validation_providers() is implemented.
 */
function addressfield_validation_install() {
  variable_set('addressfield_validation_provider', 'fedex');
}

/**
 * Implemements hook_uninstall()
 */
function addressfield_validation_uninstall() {
  variable_del('addressfield_validation_provider');
}